export const ERROR_CODES = {
  USER_OR_PASSWORD_INCORRECT: 'USER_OR_PASSWORD_INCORRECT',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_INVALID: 'TOKEN_INVALID',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS'
} as const;
